### ISSUE TITLE
Make "Delete" button more obvious

### ISSUE THREAD

**Issue by noySq** [SkEditorTeam/SkEditor#121]
When right clicking on a folder there is a button 'Delete' which is extremely misleading. I thought it would remove that folder from the program so I can open a new one, but instead it deleted my entire project without a trace. To be honest I have no idea how can I recover my files too.
![this](https://github.com/user-attachments/assets/591a96dd-d06f-43fb-8365-9177aebb84f5)

**Comment by NotroDev** [comment]
Hm, yeah, I didn't think about it.

There should be a second button to close the project, but in the current version it's not being shown because of a bug. If it'd appear correctly, probably there wouldn't be a problem like this. I'm sorry.

I'll take care of it in the next update.

**Comment by Shroobz** [comment]
bro has never used a code editor before
