### ISSUE TITLE
Make auto-pairing feature more context-aware

### ISSUE THREAD

**Issue by KwiatekMiki** [SkEditorTeam/SkEditor#15]
Let's say I write `"test"`. If I accidentally remove the last quotation mark and try to add it again, it will add 2 quotation marks instead of one with `Auto-pairing` enabled.

https://github.com/SkEditorTeam/SkEditor/assets/79092746/9612ba6c-2f64-4c75-b12d-0318e240196b

Why not make it so that it will add only one quotation mark?

**Comment by NotroDev** [comment]
Hm, I thought it works like this.
I'll do it

**Comment by NotroDev** [comment]
There are some problem with other sumbols than a quote.
Will be fixed in the next update
