### ISSUE TITLE
unrecognized function

### ISSUE THREAD

**Issue by SkJsonTeam** [SkEditorTeam/SkEditor#22]
![image](https://github.com/SkEditorTeam/SkEditor/assets/130649230/86470dbe-d070-4061-b228-0d95e53890b6)

**Comment by NotroDev** [comment]
Hi!

Do you mean that "local" is not highlighted?

**Comment by SkJsonTeam** [comment]
![image](https://github.com/SkEditorTeam/SkEditor/assets/130649230/9a4f9776-b966-4127-8022-5007bd96079f)

**Comment by NotroDev** [comment]
The Analyzer is disabled, so it won't update code info.
You need to enable it (you probably have wrong Java set, check out Analyzer settings)

**Comment by SkJsonTeam** [comment]
WHere can i set the Java? and also how can i create a addon for that?

**Comment by SkJsonTeam** [comment]
![image](https://github.com/SkEditorTeam/SkEditor/assets/130649230/e102a241-5f49-445d-82eb-e7caaa128086)

**Comment by SkJsonTeam** [comment]
![image](https://github.com/SkEditorTeam/SkEditor/assets/130649230/c58a0b78-785f-461e-829b-97f957fd6615)
![image](https://github.com/SkEditorTeam/SkEditor/assets/130649230/ea776932-0d66-4083-985b-6689e3b00eb3)

**Comment by NotroDev** [comment]
Java seems to be set correctly.

Please join our Discord server and report it there, because the Analyzer is just an addon, so it's not the best place for issues with it.
