### ISSUE TITLE
Project Subdirectories Issue

### ISSUE THREAD

**Issue by AmazinAxel** [SkEditorTeam/SkEditor#23]
The new 2.1.1 update added the projects feature (which I enabled in my settings.json). The projects feature works and I am able to select a directory to see all my files within a folder. However, I noticed a pretty major problem with how it handles subdirectories. 

When you select a folder that contains multiple other folders, you are only able to see 1 folder (and the content within that folder) and you aren't able to see other folders or any other content. Here is an example of this behavior: 

Say this is a directory tree that is opened using this new project feature:

/project/
-- folder1/
---- viewableskript.sk
---- anotherskript.sk
-- invisiblefolder/
---- nonviewableskript.sk
-- nonviewableskript.sk

When opening this folder, the directory tree will only show folder1 and its contents. It wont show any other folders or files.

In Windows, this is what my project folder looks like:
![image](https://github.com/SkEditorTeam/SkEditor/assets/87440159/aa6df090-d91e-49bc-9e9d-c5318f6b684c)

In SkEditor, this is what the folder looks like:
![image](https://github.com/SkEditorTeam/SkEditor/assets/87440159/0fe89ca7-160b-4aa2-98a5-29fcb7d9cdbb)

As you can see, folder2 and test.sk are missing from the tree. 

Other QoL improvements:
This is an amazing great start and this new project feature is so useful. I understand its still experimental and not finished, but I figured I could share a few changes that would improve this feature of the application:
- File renaming, creation, and deletion from within the project directory tree
- The option to single-click (instead of double-clicking) to open a file
- Project saving on close (whenever you close the application and reopen it, you have to reselect the directory your project is in)

Not sure if this is relevant but I'm using Windows 11 on SkEditor version 2.1.1.

Anyways, I love this new project feature and it's a step towards making SkEditor feel like an even more advanced IDE. I would love for it to be improved more but it's a great start!

**Comment by NotroDev** [comment]
That's really weird, it worked for me.
I'll look into it

**Comment by AmazinAxel** [comment]
Just wanted to say that update 2.1.2 fixed the problem and the issue is now gone. Thanks!
