### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AgentPhoenics** [SkEditorTeam/SkEditor#30]
Well, I opened it and wrote about 120 lines of code, and then when I tried to undo it (ctrl+z) and it crashed, and then reopened up, giving me my files back from the crash. Then a couple seconds later it crashed again, this time without a log, and deleted all the files I hadn't saved...

**Comment by AgentPhoenics** [comment]
Well, it crashed again due to doing ctrl+z again, and it didn't give me back the files... But then the next day I used undo again and it crashed and deleted all my current files and replaced them with the ones from yesterday...

**Comment by NotroDev** [comment]
That's weird...
Could you send me the logs?
