### ISSUE TITLE
how to update script version

### ISSUE THREAD

**Issue by BANKAYT** [SkEditorTeam/SkEditor#33]
how to update this version
![Zrzut ekranu 2024-03-02 102508](https://github.com/SkEditorTeam/SkEditor/assets/154932206/14eaa0ab-0121-41b5-b8e4-1f0059faddf6)

@NotroDev

**Comment by NotroDev** [comment]
I don't think that's possible, you need to contact @GliczDev (you can ping him on Discord server)
Analyzer is an addon, so the next time, please write on the Discord server, or its GitHub: https://github.com/SkEditorTeam/SkAnalyzer
