### ISSUE TITLE
SkEditor incomplete registry?

### ISSUE THREAD

**Issue by Brickgard** [SkEditorTeam/SkEditor#5]
Uninstalled the old SkEditorPlus 1.7.3 and installed SkEditor 2.0.5 on Windows 11.
Now when attempting to open `.sk` files, the system recommends `SkEditorPlus` despite the software being completely uninstalled.
There seems to be no way to set `.sk` files to open using the new SkEditor by default, as the only system presence seems to be the SkEditorIcon shortcut that points to the application.

Any guidance for repair, as well as registering file association with .sk files, would be appreciated.  Thanks for any insight/assistance!

**Comment by NotroDev** [comment]
There shouldn't be problems like these 🤔
Did you try to select `C:/Program Files/SkEditor/SkEditor.exe`?

**Comment by Brickgard** [comment]
That worked for associating the file type, but now SkEditor says an Update Available every time I open it.

**Comment by Brickgard** [comment]
Installed version is 2.0.5
![image](https://github.com/SkEditorTeam/SkEditor/assets/59861581/167fa79a-f2a6-428e-a6cd-2734ead10e62)
Software that opens from `C:/Program Files/SkEditor/SkEditor.exe` is 2.0.4
![image](https://github.com/SkEditorTeam/SkEditor/assets/59861581/2a14e9e9-9b31-4451-aec7-f82115f3e5b8)

**Comment by NotroDev** [comment]
That's really weird. Everything works as expected on my Windows Sandbox.
Could you just try to uninstall SkEditor, delete the SkEditor folder in Program Files if it still exists, and install the latest version?

**Comment by Brickgard** [comment]
The uninstall completely removed the folder as usual, but installing this latest (2.0.6) seems to have worked after manually associating the files.
(Windows Defender didn't like the installer publisher though, just FYI)

Thanks for the help, and for your work on this amazing tool!  ^u^

**Comment by NotroDev** [comment]
> Windows Defender didn't like the installer publisher though, just FYI
I need to send every version to the Microsoft and after a few hours they remove this warning :)

That's great that everything works now. Enjoy!
