### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by 1223nij** [SkEditorTeam/SkEditor#51]
You should add a linux version
Wine is not working

**Comment by NotroDev** [comment]
There's a Linux version, but I just don't upload it. There will be automated system in the future.
[SkEditorLinuxDebian (x64).zip](https://github.com/SkEditorTeam/SkEditor/files/15296508/SkEditorLinuxDebian.x64.zip)

**Comment by 1223nij** [comment]
do you have a fedora version?

**Comment by 1223nij** [comment]
also when i convert it using alien it says 
`
package SkEditor-2.3.1-2.arm64 from @commandline does not have a compatible architecture
`

**Comment by NotroDev** [comment]
This version should work on all Linux distributions:
https://notro.me/resources/SkEditorLinux64.zip
