### ISSUE TITLE
gui generator dosent work on 2.7.0-prerelease on windows

### ISSUE THREAD

**Issue by MCdragonmasters** [SkEditorTeam/SkEditor#85]
https://github.com/user-attachments/assets/07efcd03-4e9d-4b46-b83b-b2afcb0ed1e4

**Comment by MCdragonmasters** [comment]
ctrl+shift+G dosent make is show up either

**Comment by MCdragonmasters** [comment]
command generator dosent work either

**Comment by MCdragonmasters** [comment]
WAIt
NVM IN DUMB
had to open a file 🤦

**Comment by NotroDev** [comment]
Not a bug, you are in a welcome tab. Options from the Edit menu doesn't work.
